travis:
  secure:
    BINSTAR_TOKEN: xFxlQMPCjfA9yR5jYkXwlBSluHKZAewRVnd8x7CeSP6Yx7TJwuawTrhQoOA7vRAmLiXtrK591998X6Umaqh0VwVg61MBuyyrxewhIql/XgiVk7cKzS0R8t08FiW2LwnCcddyy2N4pnSG1vGPVYf1HL6uqRDyVRycJq1WhWNPIzaYVFxflgeTZDKWBemjy/VC9pzFJfh0EkxUS/sxgmwzjr2jmSbhcc7MCroRcvyLo6wp9WbkpznVxsfLxUT3Dj6SRRPckZzkQT8SDrFF6jHmMZzGVmYV0L9w1y5qlMEQI6PlB4V+kWoKvU7FycZM8tp/BlSS6gq1Lo4Cf3cYlwi7Z1/HNaRUZVq71H6X+bvIS1DHThNG0HG/a6ZPMsdjnYy2Db7XGJlzvgj3KcFblAZATHhSoNsmGx3hXvfmf5Q8Ps1VZyNtmec1Fott9cFYDxmyA1NU/fHO41l4H5hBuMAJ/Bh8ZHi4G839VAH1fmXRhbghORFKaGYPDBX5viIYMle9ccI9tiv5L3D31qmGWh7yiIOfi8bz7bU1zMnV6Q52T1v5YGuQ+Ox8+8ipAv/Q4PudY21nJA+VqYqNqjUFohFmmfJxNI0mA3/VbrxDszeEv1CzcysLUOI9Bq72Ydc6ScwiLD+BVokbeDnDSMF35d6EecZoOWnzumqzIp1N27i10MI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
